@startuml

left to right direction

actor GestorasDestinos as G

package GestionarReseñas {
    usecase "Ver reseñas atractivo turístico" as UC1
    usecase "Ver reseñas evento turístico" as UC2

}

G -- UC1
G -- UC2


@enduml