@startuml
left to right direction

actor Turista as T

package "UC4 - Gestionar Atractivos" {
    usecase "Buscar sitio y ver detalles" as UC1
    usecase "Recomendar lugares cercanos" as UC2
    usecase "Consultar disponibilidad\nde sitio" as UC3
    usecase "Consultar nivel de congestión" as UC4
    usecase "Ver sitios más visitados" as UC5
    usecase "Visualizar sitios en mapa" as UC6
    usecase "Filtrar atractivos por zona" as UC7
    usecase "Filtrar atractivos por categoría" as UC8
}

T -- UC1
T -- UC2
T -- UC3
T -- UC4
T -- UC5
T -- UC6
T -- UC7
T -- UC8

UC3 ..> UC1 : <<include>>
UC4 ..> UC1 : <<extend>>
UC7 ..> UC1 : <<include>>
UC8 ..> UC1 : <<include>>

@enduml
